apiVersion: v1
kind: Config
users:
- name: kube-proxy
  user:
    token: '{{ KUBE_PROXY_TOKEN }}'
clusters:
- name: local
  cluster:
     insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kube-proxy
  name: service-account-context
current-context: service-account-context
