apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ CA_CERT }}
    server: {{ KUBE_SERVER}}
  name: {{ CERT_NAME}}
contexts:
- context:
    cluster: {{ CLUSTER_NAME}}
    user: {{ CLUSTER_USER_NAME }}
  name: {{ CONTEXT_NAME}}
current-context: {{ CURRENT_CONTEXT}}
kind: Config
preferences: {}
users:
- name: {{ AUTH_NAME }}
  user:
    client-certificate-data: {{ CLIENT_CERT}}
    client-key-data: {{ CLIENT_KEY }}